// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI3LqmbE3NAK0kuwLJ42tQ0mkZXaWvqMI',
    appId: '1:849207192171:web:f303079ddbb3a13eb95f2e',
    messagingSenderId: '849207192171',
    projectId: 'toeictest-28cab',
    authDomain: 'toeictest-28cab.firebaseapp.com',
    storageBucket: 'toeictest-28cab.appspot.com',
    measurementId: 'G-D53VTMVMPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4nmhwBykREXzC8phUA1MruL7MN-ICEPo',
    appId: '1:849207192171:android:0c272858abbe558eb95f2e',
    messagingSenderId: '849207192171',
    projectId: 'toeictest-28cab',
    storageBucket: 'toeictest-28cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCES86Zt3FimZPbTwEf7g51tbtgIqB8dqk',
    appId: '1:849207192171:ios:17f9eb964ed9bd7eb95f2e',
    messagingSenderId: '849207192171',
    projectId: 'toeictest-28cab',
    storageBucket: 'toeictest-28cab.appspot.com',
    iosClientId: '849207192171-61m1ed1vmd7mm5meke0otut324tde048.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCES86Zt3FimZPbTwEf7g51tbtgIqB8dqk',
    appId: '1:849207192171:ios:17f9eb964ed9bd7eb95f2e',
    messagingSenderId: '849207192171',
    projectId: 'toeictest-28cab',
    storageBucket: 'toeictest-28cab.appspot.com',
    iosClientId: '849207192171-61m1ed1vmd7mm5meke0otut324tde048.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontEnd',
  );
}
